language: python
install:
    - pip install .
    - pip install pdoc3
script:
    - pdoc --html --force --output-dir api vectorbt
    - mv api/vectorbt/* api
    - rmdir api/vectorbt
    - rm -rf !(api)
    - "<meta http-equiv=\"refresh\" content=\"0; url=./api/index.html\" />" > index.html
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
        branch: master