language: python
install:
    - pip install .
    - pip install empyrical
    - pip install pytest-cov codecov
    - pip install pdoc3==0.8.1
script:
    - pytest tests/
    - export NUMBA_DISABLE_JIT=1  # Numba doesn't support testing yet
    - pytest --cov=vectorbt tests/
after_success:
    - codecov
    - pdoc --html --force --output-dir docs vectorbt --template-dir docs/templates
    - mv docs/vectorbt/* docs
    - rmdir docs/vectorbt
    - rm -rf !(docs)
    - echo "<meta http-equiv=\"refresh\" content=\"0; url=./docs/index.html\" />" > index.html
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
        branch: master