language: python
install:
    - pip install .
    - pip install empyrical
    - pip install pytest-cov codecov
    - pip install pdoc3==0.8.1
    - curl -O http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    - tar -xzf ta-lib-0.4.0-src.tar.gz
    - cd ta-lib/
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - pip install TA-Lib
script:
    - pytest tests/
    - export NUMBA_DISABLE_JIT=1
    - pytest --cov=vectorbt tests/
after_success:
    - codecov
    - pdoc --html --force --output-dir docs vectorbt --template-dir docs/templates
    - mv docs/vectorbt/* docs
    - rmdir docs/vectorbt
    - rm -rf !(docs)
    - echo "<meta http-equiv=\"refresh\" content=\"0; url=./docs/index.html\" />" > index.html
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master