settings:
    portfolio:
        freq: days
data: BTC-USD
indicators:
    ma1:
        type: MA
        close: data.open
        window: 10
        ewm: no
    ma2:
        type: MA
        close: data.open
        window: 20
        ewm: yes
threshold: 0
entries: indicators.ma1 - indicators.ma2 > threshold
exits: indicators.ma1 - indicators.ma2 < threshold
portfolio:
    type: Portfolio
    method: from_signals
print: portfolio.sharpe_ratio
do:
    - portfolio.returns:
        _accessor:
            year_freq: '252 days'
    - cumulative
    - plot
    - save:
        name: cumulative_returns